### ISSUE TITLE
Hidden fields doesn't work

### ISSUE THREAD

**Issue by jaynguyenit** [Mosquid/react-form-wp-cf7#2]
How can we make it work with hidden fields? because no change event on hidden fields.

**Comment by Mosquid** [comment]
It really depends on how you set values to your hidden fields. Did you consider something like this?

```
function Form({ handler, isLoading, isSent, hasError }) {
  const [formState, setFormState] = useState({
    hiddenFiled1: "value",
    hiddenField2: true,
  });

...
```
